# Generated by Django 5.2.13 on 2026-05-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='ip_address',
            field=models.CharField(blank=True, help_text='İsteğin geldiği adres (varsa).', max_length=45, verbose_name='IP adresi'),
        ),
    ]
