# Generated by Django 5.2.13 on 2026-06-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sitesettings_map_embed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('notified', models.BooleanField(default=False, verbose_name='Bildirildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Talep tarihi')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Bildirim tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Stok bildirimi talebi',
                'verbose_name_plural': 'Stok bildirimi talepleri',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'email'), name='uniq_stock_notification_product_email')],
            },
        ),
    ]
