# Generated by Django 5.2.13 on 2026-06-07 14:08

import cart.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_contactmessage_ip_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=cart.models.generate_order_number, editable=False, max_length=20, unique=True, verbose_name='Sipariş numarası')),
                ('full_name', models.CharField(max_length=160, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon')),
                ('city', models.CharField(max_length=80, verbose_name='İl')),
                ('district', models.CharField(max_length=80, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='Adres')),
                ('note', models.CharField(blank=True, max_length=400, verbose_name='Sipariş notu')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ara toplam')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Kargo')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Genel toplam')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoda'), ('delivered', 'Teslim edildi'), ('cancelled', 'İptal')], default='new', max_length=20, verbose_name='Durum')),
                ('payment_status', models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Ödeme durumu')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Kart son 4 hane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Ürün adı')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim fiyat')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Satır toplamı')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş kalemi',
                'verbose_name_plural': 'Sipariş kalemleri',
            },
        ),
    ]
